apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: root-applicationset
spec:
  generators:
  - list:
      elements:
      - appName: gitops-test
        repoURL: https://github.com/mtvier/gitops_test.git
        path: apps/
        namespace: default
      - appName: mysql-cluster
        repoURL: https://github.com/mtvier/my_k8s_service.git
        path: apps/
        namespace: my_k8s_service
  template:
    metadata:
      name: '{{appName}}'
    spec:
      project: default
      source:
        repoURL: '{{repoURL}}'
        targetRevision: HEAD
        path: '{{path}}'
        directory:
          recurse: true  # ✅ Helm wird NICHT verwendet
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
